parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(DATABASE_URL)%'
        schema_filter : '~^(?!messenger_messages)~'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Vendor:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Vendor'
                prefix: 'App\Entity\Vendor'
                alias: Vendor
            Category:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Category'
                prefix: 'App\Entity\Category'
                alias: Category
            Project:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Project'
                prefix: 'App\Entity\Project'
                alias: Project
            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Product'
                prefix: 'App\Entity\Product'
                alias: Product
            Order:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Order'
                prefix: 'App\Entity\Order'
                alias: Order

            Menu:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Menu'
                prefix: 'App\Entity\Menu'
                alias: Menu


