parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(PLATFORM_DATES_DATABASE): ''
    env(OBJECT_REVIEWS_DATABASE): ''
    env(PLATFORM_SYSTEM_DATABASE): ''
doctrine:
    dbal:
        default_connection: postgres
        connections:
            postgres:
                # configure these for your database server
                # this connectors for all project's information
                url: '%env(PLATFORM_DATES_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                schema_filter: '~^(?!messenger_messages)~'
            review:
                url: '%env(resolve:OBJECT_REVIEWS_DATABASE)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
            sqllite:
                # configure these for your database server
                # this connector for all modules, menus, parameters of system
                url: '%env(resolve:PLATFORM_SYSTEM_DATABASE)%'
                driver: 'pdo_sqlite'
                server_version: '3.21'
                charset: utf8mb4
    orm:
        # auto_generate_proxy_classes: '%kernel.debug%'
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        # auto_mapping: true
        default_entity_manager: postgres
        entity_managers:
            postgres:
                connection: postgres
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    Vendor:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Vendor'
                        prefix: 'App\Entity\Vendor'
                        alias: Vendor
                    Category:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category
                    Project:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: Project
                    Product:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: Product
                    Order:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Order'
                        prefix: 'App\Entity\Order'
                        alias: Order
                    Folder:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Folder'
                        prefix: 'App\Entity\Folder'
                        alias: Folder
                    Commission:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Commission'
                        prefix: 'App\Entity\Commission'
                        alias: Commission
                    Event:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Event'
                        prefix: 'App\Entity\Event'
                        alias: Event
                    Message:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Message'
                        prefix: 'App\Entity\Message'
                        alias: Message
                    Tag:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Tag'
                        prefix: 'App\Entity\Tag'
                        alias: Tag
            review:
                connection: review
                mappings:
                    Product:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Review'
                        prefix: 'App\Entity\Review'
                        alias: ProductReviews
                    Project:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Review'
                        prefix: 'App\Entity\Review'
                        alias: ProjectReviews
            sqllite:
                connection: sqllite
                mappings:
                    Menu:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Menu'
                        prefix: 'App\Entity\Menu'
                        alias: Menu
                    Module:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Module'
                        prefix: 'App\Entity\Module'
                        alias: Module
                    Category:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category
