parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(SQL_LITE_DATABASE_URL): ''
    env(MY_SQL_PRODUCT_REVIEWS_DATABASE_URL): ''
    env(MY_SQL_PROJECT_REVIEWS_DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: postgres
        connections:
            postgres:
                # configure these for your database server
                # this connectors for all project's information
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '11.2'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                schema_filter: '~^(?!messenger_messages)~'
            sqllite:
                # configure these for your database server
                # this connector for all modules, menus, parameters of system
                url: '%env(resolve:SQL_LITE_DATABASE_URL)%'
                driver: 'pdo_sqlite'
                server_version: '3.21'
                charset: utf8mb4
            product_reviews:
                url: '%env(resolve:MY_SQL_PRODUCT_REVIEWS_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '3.21'
                charset: utf8mb4
            project_reviews:
                url: '%env(resolve:MY_SQL_PROJECT_REVIEWS_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '3.21'
                charset: utf8mb4
    orm:
        # auto_generate_proxy_classes: '%kernel.debug%'
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        # auto_mapping: true
        default_entity_manager: postgres
        entity_managers:
            postgres:
                connection: postgres
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    Vendor:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Vendor'
                        prefix: 'App\Entity\Vendor'
                        alias: Vendor
                    Category:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category
                    Project:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: Project
                    Product:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Product'
                        prefix: 'App\Entity\Product'
                        alias: Product
                    Order:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Order'
                        prefix: 'App\Entity\Order'
                        alias: Order
            product_reviews:
                connection: product_reviews
                mappings:
                    Product_review:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Review/ProductReviews'
                        prefix: 'App\Entity\Review\ProductReviews\ProductReviews'
                        alias: Product_Reviews
            project_reviews:
                connection: project_reviews
                mappings:
                    Project_review:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Review/ProjectReviews'
                        prefix: 'App\Entity\Review\Review\ProjectReviews'
                        alias: ProjectReviews
            sqllite:
                connection: sqllite
                mappings:
                    Menu:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Menu'
                        prefix: 'App\Entity\Menu'
                        alias: Menu
                    Module:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Module'
                        prefix: 'App\Entity\Module'
                        alias: Module
                    Category:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Category'
                        prefix: 'App\Entity\Category'
                        alias: Category