framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true
    default_locale: '%locale%'
    #translator:
    #    default_path: '%kernel.project_dir%/translations'
    #    fallbacks:
    #    - '%locale%'
    #    paths:
    #    - '%kernel.project_dir%/translations/en-GB'
    #    - '%kernel.project_dir%/translations/ru-RU'
    #    - '%kernel.project_dir%/translations/uk-UA'

    router:
        strict_requirements: ~
        utf8: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # The 'ide' option turns all of the file paths in an exception page
    # into clickable links that open the given file using your favorite IDE.
    # When 'ide' is set to null the file is opened in your web browser.
    # See https://symfony.com/doc/current/reference/configuration/framework.html#ide
    ide: ~
    validation:
        email_validation_mode: 'html5'
        enable_annotations: true
