framework:
    validation: { enable_annotations: true }
        # email_validation_mode: html5
        auto_mapping:
            App\Entity\: []
            App\Entity\Category: []
            App\Entity\Product: []
            App\Entity\Project: []
            App\Entity\Order: []
            App\Entity\Vendor: []
