homepage:
  path: /
  controller: App\Controller\HomepageController::index

"https://{all}/": { type: upstream, upstream: "varnish:http", cache: { enabled: false } }
"http://{all}/": { type: redirect, to: "https://{all}/" }
